name: Deploy to Cloudsmith

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install setuptools wheel

    - name: Build package
      run: python setup.py bdist_wheel

    - name: Authenticate with Cloudsmith using OIDC
      env:
        CLOUDSMITH_TOKEN: ${{ secrets.CLOUDSMITH_TOKEN }}
      run: echo "OIDC Authentication Completed."

    - name: Push package to Cloudsmith
      uses: cloudsmith-io/github-action@v3
      with:
        owner: interview-keshav
        repo: your-cloudsmith-repo
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}

